part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const NEW_PASSWORD = _Paths.NEW_PASSWORD;
  static const TAMBAH_PEGAWAI = _Paths.TAMBAH_PEGAWAI;
  static const TAMBAH_KELOMPOK_MENGAJI = _Paths.TAMBAH_KELOMPOK_MENGAJI;
  static const TAMBAH_SISWA = _Paths.TAMBAH_SISWA;
  static const DAFTAR_KELAS = _Paths.DAFTAR_KELAS;
  static const DAFTAR_HALAQOH_PENGAMPU = _Paths.DAFTAR_HALAQOH_PENGAMPU;
  static const PEMBERIAN_KELAS_SISWA = _Paths.PEMBERIAN_KELAS_SISWA;
  static const KELOMPOK_HALAQOH = _Paths.KELOMPOK_HALAQOH;
  static const DAFTAR_HALAQOH_PERFASE = _Paths.DAFTAR_HALAQOH_PERFASE;
  static const DAFTAR_SISWA_PINDAH_HALAQOH = _Paths.DAFTAR_SISWA_PINDAH_HALAQOH;
  static const DAFTAR_HALAQOH = _Paths.DAFTAR_HALAQOH;
  static const DAFTAR_NILAI = _Paths.DAFTAR_NILAI;
  static const PEMBERIAN_NILAI_HALAQOH = _Paths.PEMBERIAN_NILAI_HALAQOH;
  static const DETAIL_SISWA = _Paths.DETAIL_SISWA;
  static const DETAIL_NILAI_HALAQOH = _Paths.DETAIL_NILAI_HALAQOH;
  static const PEMBERIAN_GURU_MAPEL = _Paths.PEMBERIAN_GURU_MAPEL;
  static const MAPEL_SISWA = _Paths.MAPEL_SISWA;
  static const JURNAL_AJAR_HARIAN = _Paths.JURNAL_AJAR_HARIAN;
  static const INPUT_INFO_SEKOLAH = _Paths.INPUT_INFO_SEKOLAH;
  static const TAMPILKAN_INFO_SEKOLAH = _Paths.TAMPILKAN_INFO_SEKOLAH;
  static const DAFTAR_SISWA_PERKELAS = _Paths.DAFTAR_SISWA_PERKELAS;
  static const INPUT_CATATAN_KHUSUS_SISWA = _Paths.INPUT_CATATAN_KHUSUS_SISWA;
  static const TANGGAPAN_CATATAN_KHUSUS_SISWA =
      _Paths.TANGGAPAN_CATATAN_KHUSUS_SISWA;
  static const TANGGAPAN_CATATAN_KHUSUS_SISWA_WALIKELAS =
      _Paths.TANGGAPAN_CATATAN_KHUSUS_SISWA_WALIKELAS;
  static const DAFTAR_SISWA_PERMAPEL = _Paths.DAFTAR_SISWA_PERMAPEL;
  static const PEMBAYARAN_SPP = _Paths.PEMBAYARAN_SPP;
  static const DAFTAR_HALAQOHNYA = _Paths.DAFTAR_HALAQOHNYA;
  static const JADWAL_PELAJARAN = _Paths.JADWAL_PELAJARAN;
  static const BUAT_JADWAL_PELAJARAN = _Paths.BUAT_JADWAL_PELAJARAN;
  static const BUAT_SARPRAS = _Paths.BUAT_SARPRAS;
  static const DATA_SARPRAS = _Paths.DATA_SARPRAS;
  static const DAFTAR_EKSKUL = _Paths.DAFTAR_EKSKUL;
  static const TANGGAPAN_CATATAN = _Paths.TANGGAPAN_CATATAN;
  static const REKAPITULASI_PEMBAYARAN = _Paths.REKAPITULASI_PEMBAYARAN;
  static const REKAPITULASI_PEMBAYARAN_RINCI =
      _Paths.REKAPITULASI_PEMBAYARAN_RINCI;
  static const IMPORT_SISWA_EXCEL = _Paths.IMPORT_SISWA_EXCEL;
  static const CATATAN_SISWA = _Paths.CATATAN_SISWA;
  static const KALENDER_AKADEMIK = _Paths.KALENDER_AKADEMIK;
  static const INPUT_EKSKUL = _Paths.INPUT_EKSKUL;
  static const DAFTAR_JURNAL_AJAR = _Paths.DAFTAR_JURNAL_AJAR;
  static const ABSENSI = _Paths.ABSENSI;
  static const PRANGKAT_AJAR = _Paths.PRANGKAT_AJAR;
  static const PERANGKAT_AJAR = _Paths.PERANGKAT_AJAR;
  static const ATP_FORM = _Paths.ATP_FORM;
  static const MODUL_AJAR_FORM = _Paths.MODUL_AJAR_FORM;
  static const PROTA_PROSEM = _Paths.PROTA_PROSEM;
  static const IMPORT_PEGAWAI = _Paths.IMPORT_PEGAWAI;
  static const INPUT_NILAI_SISWA = _Paths.INPUT_NILAI_SISWA;
  static const RAPOR_SISWA = _Paths.RAPOR_SISWA;
  static const KELAS_TAHFIDZ = _Paths.KELAS_TAHFIDZ;
  static const REKAP_JURNAL_GURU = _Paths.REKAP_JURNAL_GURU;
  static const REKAP_JURNAL_ADMIN = _Paths.REKAP_JURNAL_ADMIN;
  static const LAKSANAKAN_UJIAN = _Paths.LAKSANAKAN_UJIAN;
  static const REKAP_ABSENSI = _Paths.REKAP_ABSENSI;
  static const ANALISIS_AKADEMIK = _Paths.ANALISIS_AKADEMIK;
  static const MANAJEMEN_JABATAN = _Paths.MANAJEMEN_JABATAN;
  static const MANAJEMEN_TUGAS = _Paths.MANAJEMEN_TUGAS;
  static const DAFTAR_PEGAWAI = _Paths.DAFTAR_PEGAWAI;
  static const PANTAU_TAHFIDZ = _Paths.PANTAU_TAHFIDZ;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const NEW_PASSWORD = '/new-password';
  static const TAMBAH_PEGAWAI = '/tambah-pegawai';
  static const TAMBAH_KELOMPOK_MENGAJI = '/tambah-kelompok-mengaji';
  static const TAMBAH_SISWA = '/tambah-siswa';
  static const DAFTAR_KELAS = '/daftar-kelas';
  static const DAFTAR_HALAQOH_PENGAMPU = '/daftar-halaqoh-pengampu';
  static const PEMBERIAN_KELAS_SISWA = '/pemberian-kelas-siswa';
  static const KELOMPOK_HALAQOH = '/kelompok-halaqoh';
  static const DAFTAR_HALAQOH_PERFASE = '/daftar-halaqoh-perfase';
  static const DAFTAR_SISWA_PINDAH_HALAQOH = '/daftar-siswa-pindah-halaqoh';
  static const DAFTAR_HALAQOH = '/daftar-halaqoh';
  static const DAFTAR_NILAI = '/daftar-nilai';
  static const PEMBERIAN_NILAI_HALAQOH = '/pemberian-nilai-halaqoh';
  static const DETAIL_SISWA = '/detail-siswa';
  static const DETAIL_NILAI_HALAQOH = '/detail-nilai-halaqoh';
  static const PEMBERIAN_GURU_MAPEL = '/pemberian-guru-mapel';
  static const MAPEL_SISWA = '/mapel-siswa';
  static const JURNAL_AJAR_HARIAN = '/jurnal-ajar-harian';
  static const INPUT_INFO_SEKOLAH = '/input-info-sekolah';
  static const TAMPILKAN_INFO_SEKOLAH = '/tampilkan-info-sekolah';
  static const DAFTAR_SISWA_PERKELAS = '/daftar-siswa-perkelas';
  static const INPUT_CATATAN_KHUSUS_SISWA = '/input-catatan-khusus-siswa';
  static const TANGGAPAN_CATATAN_KHUSUS_SISWA =
      '/tanggapan-catatan-khusus-siswa';
  static const TANGGAPAN_CATATAN_KHUSUS_SISWA_WALIKELAS =
      '/tanggapan-catatan-khusus-siswa-walikelas';
  static const DAFTAR_SISWA_PERMAPEL = '/daftar-siswa-permapel';
  static const PEMBAYARAN_SPP = '/pembayaran-spp';
  static const DAFTAR_HALAQOHNYA = '/daftar-halaqohnya';
  static const JADWAL_PELAJARAN = '/jadwal-pelajaran';
  static const BUAT_JADWAL_PELAJARAN = '/buat-jadwal-pelajaran';
  static const BUAT_SARPRAS = '/buat-sarpras';
  static const DATA_SARPRAS = '/data-sarpras';
  static const DAFTAR_EKSKUL = '/daftar-ekskul';
  static const TANGGAPAN_CATATAN = '/tanggapan-catatan';
  static const REKAPITULASI_PEMBAYARAN = '/rekapitulasi-pembayaran';
  static const REKAPITULASI_PEMBAYARAN_RINCI = '/rekapitulasi-pembayaran-rinci';
  static const IMPORT_SISWA_EXCEL = '/import-siswa-excel';
  static const CATATAN_SISWA = '/catatan-siswa';
  static const KALENDER_AKADEMIK = '/kalender-akademik';
  static const INPUT_EKSKUL = '/input-ekskul';
  static const DAFTAR_JURNAL_AJAR = '/daftar-jurnal-ajar';
  static const ABSENSI = '/absensi';
  static const PRANGKAT_AJAR = '/prangkat-ajar';
  static const PERANGKAT_AJAR = '/perangkat-ajar';
  static const ATP_FORM = '/atp-form';
  static const MODUL_AJAR_FORM = '/modul-ajar-form';
  static const PROTA_PROSEM = '/prota-prosem';
  static const IMPORT_PEGAWAI = '/import-pegawai';
  static const INPUT_NILAI_SISWA = '/input-nilai-siswa';
  static const RAPOR_SISWA = '/rapor-siswa';
  static const KELAS_TAHFIDZ = '/kelas-tahfidz';
  static const REKAP_JURNAL_GURU = '/rekap-jurnal-guru';
  static const REKAP_JURNAL_ADMIN = '/rekap-jurnal-admin';
  static const LAKSANAKAN_UJIAN = '/laksanakan-ujian';
  static const REKAP_ABSENSI = '/rekap-absensi';
  static const ANALISIS_AKADEMIK = '/analisis-akademik';
  static const MANAJEMEN_JABATAN = '/manajemen-jabatan';
  static const MANAJEMEN_TUGAS = '/manajemen-tugas';
  static const DAFTAR_PEGAWAI = '/daftar-pegawai';
  static const PANTAU_TAHFIDZ = '/pantau-tahfidz';
}
